# Generated by Django 5.2.13 on 2026-04-22 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='planmedicacion',
            name='stock_actual',
            field=models.IntegerField(default=0, help_text='Pastillas traídas por la familia'),
        ),
    ]
