# Generated by Django 5.2.13 on 2026-04-23 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_planmedicacion_stock_actual'),
    ]

    operations = [
        migrations.AddField(
            model_name='residente',
            name='condicion_deglucion',
            field=models.CharField(blank=True, default='Normal', help_text='Ej: Normal, Molido, Sonda', max_length=200),
        ),
        migrations.AddField(
            model_name='residente',
            name='contacto_familiar',
            field=models.CharField(blank=True, help_text='Nombre y Teléfono', max_length=200),
        ),
        migrations.AddField(
            model_name='residente',
            name='diagnostico_principal',
            field=models.CharField(blank=True, default='No especificado', max_length=200),
        ),
    ]
